[general]
threads = 0

[data]
# Top-level paths
data = "data"

# Data subdirectories
clust = "clust"
genes = "genes"
go = "go"
plots = "plots"
star = "star"
tom = "tom"
genesFungi = "data/genes/ptr"

[analyses]
contrast = "groupCultivarTime" # See meta.tsv for valid contrasts
pca = true
sdeg = true

go_tf = true
go_cwde = true
go_defence = true
go_transport = true
go_intracellular_signalling = true
go_kinases = true
go_chromatin = true
go_methylation = true
go_rnai = true
go_transposons = true
effectors = true

[factors]
# Apply "Ordered" after a factor name to override the factor order
control = ["control", "disease"]
cultivar = ["Machete", "Magenta", "Phantom", "Wyalkatchem", "Yitpi", "ZWB11Q56", "ZWB12Q89"]
cultivarOrdered = ["Machete", "Phantom", "Yitpi", "Wyalkatchem", "Magenta", "ZWB11Q56", "ZWB12Q89"]
rating = ["SVS", "MS", "MR", "R"]
time = ["early", "late"]

[fungi]
species = "ptr"
counts = "data/ptr.tsv"
meta = "data/ptrMeta.tsv"
traits = "data/ptrTraits.tsv"
factors = ["time", "cultivar"] # See meta.tsv for factor names, order independent
extraFactors = ["rating"] # Secondary/supplementary analysis, not used for linear factors
hkg = "actin" # Make sure house-keeping gene is also defined in genes.toml!
nreps = 3
